### ISSUE TITLE
你好！！！

### ISSUE THREAD

**Issue by oe77** [hpp38122/h#1]
你修改完的不局限扫描Google IP版的MotherFuckerFang和checkgoogleip能否共享一下给我，，我和你的出发点都是一样，用于其它需翻墙服务！

**Comment by hpp38122** [comment]
MotherFuckerFang 我不会修改

关于用checkip.py查询其他IP
找到这一行 g_ssldomain = ("google.com")
修改google.com为要查询的IPInc/CN值就可以了
这个名称怎么称呼不知道啊……不是码农不懂这些……

因为要找的IP不同所以还是要你自己修改了，其实不修改也可以的，查找过能连通的IP都在这个ip_tmpno.txt文件中，自己搜索要翻的域名就有对应的ip了。前提在googleip.txt文件中放对应的ip段

**Comment by oe77** [comment]
@hpp38122 好的，，我以为你 跟我一样寻找稀有透明代理IP，MotherFuckerFang修改了吗？拿它单单扫google IP确实浪费，可以拿它分类IP国家确实是一利器

**Comment by hpp38122** [comment]
MotherFuckerFang 不会修改，好像是C#写的
稀有ip都是直接扫描一个国家的全部ip原程序就很好用了
我修改来是找ip用于hosts文件的
最近在学python的代码，想给goagent的dnsproxy.py增加hosts指定域名IP功能

**Comment by oe77** [comment]
@hpp38122 哥们，那个IPInc/CN值在那查找？

**Comment by oe77** [comment]
g_ssldomain = ("google.com",)
g_organizationName = ("Google Inc",)
修改上面的值还是下面的值？

**Comment by hpp38122** [comment]
IPInc / CN值，用以下命令
openssl s_client -connect talk.google.com:443

g_ssldomain = ("google.com",)修改这里

**Comment by oe77** [comment]
@hpp38122 已经弄好，，谢谢你
